name: trackflow
description: "TrackFlow — a glassmorphic budget & expense tracker built with Clean Architecture + BLoC."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5          # State management
  bloc: ^8.1.4                  # State management
  equatable: ^2.0.5             # State management
  go_router: ^14.2.0            # Navigation
  sqflite: ^2.3.3               # Local persistence
  path: ^1.9.0                  # Path helpers
  intl: ^0.19.0                 # Formatting
  google_fonts: ^6.2.1          # Typography

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true